test:
  secret_key_base: f9b442692a7b96308bc594a3c53e1bc040c49e817a3a9badcb3b518df356e90f22ade231cf150e0cc72d3eb01f9c6b6096878d17221c87854d54903ac449f070
  google:
    geocoding_key: test
  geocode:
    geocoding_api: test
    geocoding_region: test

development:
  secret_key_base: e6201f8b3d37db0f142ab05142d2a77b25e2bce384e0b421bdd5a229a4c7a2b766f2f3959f6b599cf8e110960b03a78ccfed4a3c5c3b72c718dde4a755b3938b
  google:
    geocoding_key: test
  geocode:
    geocoding_api: <%= ENV["GEOCODING_API"] || 'osm' %>
    geocoding_region: <%= ENV["GOOGLE_GEOCODING_REGION"] || 'de' %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google:
    geocoding_key: <%= ENV["GOOGLE_GEOCODING_KEY"] %>
  geocode:
    geocoding_api: <%= ENV["GEOCODING_API"] || 'osm' %>
    geocoding_region: <%= ENV["GOOGLE_GEOCODING_REGION"] || 'de' %>
